version: '3'
name: api-solid

services:
  api-solid-pg:
    image: bitnami/postgresql:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=api_solid
