name: Run e2e tests

on: [pull_request]

jobs:
    run-unit-tests:
        name: Run unit tests
        runs-on: ubuntu-latest

        services:
          postgres:
            image: bitnami/postgresql:14
            ports:
              - 5432:5432
            env:
              POSTGRES_USER: docker
              POSTGRES_PASSWORD: docker
              POSTGRES_DB: api_solid

        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: '18'
            cache: 'npm'

        - run: npm ci

        - run: npm run test:e2e
          env:
            CI: true
            JWT_SECRET: testing
            DATABASE_URL: "postgresql://docker:docker@localhost:5432/api_solid?schema=public"
